// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartParkingAssistant.Server.Data;

#nullable disable

namespace SmartParkingAssistant.Server.Migrations
{
    [DbContext(typeof(SmartParkingAssistantDbContext))]
    [Migration("20251123162707_AddProperties")]
    partial class AddProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SmartParkingAssistant.Server.Models.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("BookingId");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SmartParkingAssistant.Server.Models.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 2,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 3,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 4,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 5,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 6,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 7,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 8,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 9,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 10,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 11,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 12,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 13,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 14,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 15,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 16,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 17,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 18,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 19,
                            IsOccupied = false,
                            IsReserved = false
                        },
                        new
                        {
                            Id = 20,
                            IsOccupied = false,
                            IsReserved = false
                        });
                });

            modelBuilder.Entity("SmartParkingAssistant.Server.Models.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartParkingAssistant.Server.Models.Entities.Booking", b =>
                {
                    b.HasOne("SmartParkingAssistant.Server.Models.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("Bookings")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartParkingAssistant.Server.Models.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParkingSpot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParkingAssistant.Server.Models.Entities.ParkingSpot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SmartParkingAssistant.Server.Models.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
